In [17]:
import pandas as pd 
df = pd.read_csv('Sample - Superstore.csv', encoding='latin-1')
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

## Done Group by single & multiple columns 
✅ GroupBy Single
✅ GroupBy Multiple
✅ agg()

## TOPIC - TRANSFORM

In [18]:
# difference agg() and transform 
# agg - rows decrease 
df.groupby("Category")["Sales"].sum()

# 3 rows

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [19]:
# transform rows same category at every label
df['Category_Total'] = df.groupby("Category")['Sales'].transform("sum")
df.sample(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Category_Total
9143,9144,US-2017-166688,5/20/2017,5/26/2017,Standard Class,RD-19480,Rick Duston,Consumer,United States,Las Vegas,...,West,TEC-PH-10004094,Technology,Phones,Motorola L703CM,1123.128,9,0.2,70.1955,836154.033
9036,9037,CA-2015-166492,4/7/2015,4/10/2015,First Class,RP-19390,Resi Pölking,Consumer,United States,New York City,...,East,OFF-PA-10002262,Office Supplies,Paper,Xerox 192,25.920,4,0.0,12.4416,719047.032
2012,2013,CA-2015-155761,12/11/2015,12/11/2015,Same Day,SC-20800,Stuart Calhoun,Consumer,United States,Houston,...,Central,OFF-ST-10000943,Office Supplies,Storage,Eldon ProFile File 'N Store Portable File Tub ...,46.344,3,0.2,4.6344,719047.032

In [20]:
# sales cateogry distribution
df["Category_Total"] = (
    df.groupby("Category")["Sales"]
      .transform("sum")
)
df["Contribution_%"] = (
    df["Sales"] /
    df["Category_Total"]
) * 100

In [21]:
# question - category wise average sales  every row 
df['Avg_Sales']=(df.groupby("Category")["Sales"].transform('mean'))

# question region profit every row 
df['Region_Profit']=(df.groupby("Region")['Profit'].transform("sum"))

In [22]:
# rank find 
df['Rank']=df.groupby("Category")['Sales'].rank(ascending=False)

## agg()- summary table ,
transform() -- original rows + group calciulation

## Pivot Table 
df.groupby("Region")["Sales"].sum()

-- pivot 
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    aggfunc="sum"
)

In [23]:
## Question - Region wise Sales 
# in pivot table
# syntax - pd.pivot_table(df,values='sales',index = 'region',aggfunc='sum)

pd.pivot_table(df,values='Sales',index="Region",aggfunc="sum")

               Sales
Region
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245

In [24]:
# ques - category wise profit 
pd.pivot_table(df,values="Profit",index="Category",aggfunc="sum")

                      Profit
Category
Furniture         18451.2728
Office Supplies  122490.8008
Technology       145454.9481

In [25]:
# two dimensions 
# question - region vs category
pd.pivot_table(df,values="Profit",index='Region',columns='Category',aggfunc='sum')

Category   Furniture  Office Supplies  Technology
Region
Central   -2871.0494        8879.9799  33697.4320
East       3046.1658       41014.5791  47462.0351
South      6771.2061       19986.3928  19991.8314
West      11504.9503       52609.8490  44303.6496

In [26]:
# multiple aggregation sales sum + mean
pd.pivot_table(df,values="Sales",index="Category",aggfunc=['sum','mean'])

                         sum        mean
                       Sales       Sales
Category
Furniture        741999.7953  349.834887
Office Supplies  719047.0320  119.324101
Technology       836154.0330  452.709276

In [27]:
# Fill missing 
pd.pivot_table(df,values="Sales",index='Region',columns='Category',aggfunc='sum',fill_value=0)

Category    Furniture  Office Supplies  Technology
Region
Central   163797.1638       167026.415  170416.312
East      208291.2040       205516.055  264973.981
South     117298.6840       125651.313  148771.908
West      252612.7435       220853.249  251991.832

In [28]:
# margin grand total
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="sum",
    margins=True
)

Category    Furniture  Office Supplies  Technology           All
Region
Central   163797.1638       167026.415  170416.312  5.012399e+05
East      208291.2040       205516.055  264973.981  6.787812e+05
South     117298.6840       125651.313  148771.908  3.917219e+05
West      252612.7435       220853.249  251991.832  7.254578e+05
All       741999.7953       719047.032  836154.033  2.297201e+06

In [29]:
# question - region vs segment unique customers
pd.pivot_table(df,values='Customer Name',aggfunc='nunique',columns='Segment',index='Region')

Segment  Consumer  Corporate  Home Office
Region
Central       328        180          121
East          344        206          124
South         276        152           84
West          358        204          124

Group by - best for analysis pivot table for reports and dashboards

## String function .str 
function - str.lower - lowercase letter , upper , title - new york - New York ,  strip ( exra spacses remove ) ,contains , casae insensitive , str.len , replace3

In [36]:
df['Product Name'].str.lower()
df['City'].str.upper()
df['City'].str.title()
df['City'].str.strip().head(4)  
# extra spaces remove

df[df['Product Name'].str.contains("Chair")]
# contains chair product 

df[df['Product Name'].str.contains("chair",case=False)]

# str.len -- lenght count
df['Product Name'].str.len()

# str.replace()
df['City'].str.replace("New York","NY")

# str.split()
# df['director'].str.split(",")

# question 3 - Product names > 40 chars 
df[df['Product Name'].str.len()>40]

# customer name lowercase 
df['Customer Name'].str.lower()

# products containing desk and sales > 500
df[
    df["Product Name"].str.contains(
        "Desk",
        case=False
    )
    &
    (df["Sales"]>500)
]
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Category_Total,Contribution_%,Avg_Sales,Region_Profit,Rank
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,741999.7953,0.035305,349.834887,46749.4303,831.5
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,741999.7953,0.098644,349.834887,46749.4303,277.0
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714,719047.0320,0.002033,119.324101,108418.4489,4130.5

In [43]:
# Datetime order date ship date 
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Order Date']

# to year
df['Order Date'].dt.year

# month 
df['Order Date'].dt.month

#
df["Order Date"].dt.day 

df["Order Date"].dt.quarter

df["Order Date"].dt.weekday

# new column
df["Year"] = df["Order Date"].dt.year

In [53]:
# sales by year 
df.groupby(df['Order Date'].dt.year)['Sales'].sum()

# sales by month 
df.groupby(df['Order Date'].dt.month)['Sales'].sum()

# technology sales in 2017  
df[(df['Order Date'].dt.year==2017) &
(df['Category']=='Technology')].head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Category_Total,Contribution_%,Avg_Sales,Region_Profit,Rank,Year
41,42,CA-2017-120999,2017-09-10,9/15/2017,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Naperville,...,147.168,4,0.2,16.5564,836154.033,0.017601,452.709276,39706.3625,999.0,2017
86,87,CA-2017-155558,2017-10-26,11/2/2017,Standard Class,PG-18895,Paul Gonzalez,Consumer,United States,Rochester,...,19.990,1,0.0,6.7966,836154.033,0.002391,452.709276,39706.3625,1751.0,2017
106,107,CA-2017-119004,2017-11-23,11/28/2017,Standard Class,JM-15250,Janet Martin,Consumer,United States,Charlotte,...,74.112,8,0.2,17.6016,836154.033,0.008863,452.709276,46749.4303,1335.0,2017