In [3]:
import pandas as pd 
df = pd.read_csv('Sample - Superstore.csv', encoding='latin-1')
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

## Done Group by single & multiple columns 
✅ GroupBy Single
✅ GroupBy Multiple
✅ agg()

## TOPIC - TRANSFORM

In [4]:
# difference agg() and transform 
# agg - rows decrease 
df.groupby("Category")["Sales"].sum()

# 3 rows

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [5]:
# transform rows same category at every label
df['Category_Total'] = df.groupby("Category")['Sales'].transform("sum")
df.sample(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Category_Total
1892,1893,CA-2017-145310,12/22/2017,12/24/2017,Second Class,JP-15520,Jeremy Pistek,Consumer,United States,Port Orange,...,South,OFF-EN-10002621,Office Supplies,Envelopes,Staple envelope,7.824,1,0.2,2.9340,719047.032
6499,6500,CA-2015-103135,7/24/2015,7/28/2015,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,...,South,TEC-AC-10003289,Technology,Accessories,Anker Ultra-Slim Mini Bluetooth 3.0 Wireless K...,279.860,14,0.0,64.3678,836154.033
3321,3322,CA-2014-134551,12/20/2014,12/25/2014,Standard Class,TS-21505,Tony Sayre,Consumer,United States,Columbia,...,South,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,25.920,5,0.2,9.0720,719047.032

In [6]:
# sales cateogry distribution
df["Category_Total"] = (
    df.groupby("Category")["Sales"]
      .transform("sum")
)
df["Contribution_%"] = (
    df["Sales"] /
    df["Category_Total"]
) * 100

In [7]:
# question - category wise average sales  every row 
df['Avg_Sales']=(df.groupby("Category")["Sales"].transform('mean'))

# question region profit every row 
df['Region_Profit']=(df.groupby("Region")['Profit'].transform("sum"))

In [8]:
# rank find 
df['Rank']=df.groupby("Category")['Sales'].rank(ascending=False)

## agg()- summary table ,
transform() -- original rows + group calciulation

## Pivot Table 
df.groupby("Region")["Sales"].sum()

-- pivot 
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    aggfunc="sum"
)

In [9]:
## Question - Region wise Sales 
# in pivot table
# syntax - pd.pivot_table(df,values='sales',index = 'region',aggfunc='sum)

pd.pivot_table(df,values='Sales',index="Region",aggfunc="sum")

               Sales
Region
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245

In [10]:
# ques - category wise profit 
pd.pivot_table(df,values="Profit",index="Category",aggfunc="sum")

                      Profit
Category
Furniture         18451.2728
Office Supplies  122490.8008
Technology       145454.9481

In [11]:
# two dimensions 
# question - region vs category
pd.pivot_table(df,values="Profit",index='Region',columns='Category',aggfunc='sum')

Category   Furniture  Office Supplies  Technology
Region
Central   -2871.0494        8879.9799  33697.4320
East       3046.1658       41014.5791  47462.0351
South      6771.2061       19986.3928  19991.8314
West      11504.9503       52609.8490  44303.6496

In [12]:
# multiple aggregation sales sum + mean
pd.pivot_table(df,values="Sales",index="Category",aggfunc=['sum','mean'])

                         sum        mean
                       Sales       Sales
Category
Furniture        741999.7953  349.834887
Office Supplies  719047.0320  119.324101
Technology       836154.0330  452.709276

In [13]:
# Fill missing 
pd.pivot_table(df,values="Sales",index='Region',columns='Category',aggfunc='sum',fill_value=0)

Category    Furniture  Office Supplies  Technology
Region
Central   163797.1638       167026.415  170416.312
East      208291.2040       205516.055  264973.981
South     117298.6840       125651.313  148771.908
West      252612.7435       220853.249  251991.832

In [14]:
# margin grand total
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="sum",
    margins=True
)

Category    Furniture  Office Supplies  Technology           All
Region
Central   163797.1638       167026.415  170416.312  5.012399e+05
East      208291.2040       205516.055  264973.981  6.787812e+05
South     117298.6840       125651.313  148771.908  3.917219e+05
West      252612.7435       220853.249  251991.832  7.254578e+05
All       741999.7953       719047.032  836154.033  2.297201e+06

In [15]:
# question - region vs segment unique customers
pd.pivot_table(df,values='Customer Name',aggfunc='nunique',columns='Segment',index='Region')

Segment  Consumer  Corporate  Home Office
Region
Central       328        180          121
East          344        206          124
South         276        152           84
West          358        204          124

Group by - best for analysis pivot table for reports and dashboards

## String function .str 
function - str.lower - lowercase letter , upper , title - new york - New York ,  strip ( exra spacses remove ) ,contains , casae insensitive , str.len , replace3

In [ ]:
df['Product Name'].str.lower()
df['City'].str.upper()
df['City'].str.title()
df['City'].str.strip().head(4)  
# extra spaces remove

df[df['Product Name'].str.contains("Chair")]
# contains chair product 

df[df['Product Name'].str.contains("chair",case=False)]

# str.len -- lenght count
df['Product Name'].str.len()

#

0       33
1       59
2       57
3       45
4       30
        ..
9989    22
9990    50
9991    21
9992    49
9993    73
Name: Product Name, Length: 9994, dtype: int64